apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bluedock-boot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bluedock-boot
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bluedock-worker-notify
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bluedock-worker-notify
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bluedock-worker-index
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bluedock-worker-index
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
